<a href="https://colab.research.google.com/github/nureeee/numpy-pandas/blob/main/210520_%EC%98%A4%ED%9B%84%EA%B3%BC%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [13]:
pd1 = pd.read_csv('/content/sample_data/pop.csv')

In [14]:
pd1

         기간    자치구   전입 남자   전입 여자   전출 남자   전출 여자
0   2021.03  서울특별시  73,389  78,228  77,842  79,991
1   2021.03    종로구   1,266   1,378   1,353   1,344
2   2021.03     중구     949   1,017   1,075   1,069
3   2021.03    용산구   2,111   2,351   1,942   1,940
4   2021.03    성동구   2,282   2,374   2,575   2,466
5   2021.03    광진구   2,551   2,881   2,775   3,052
6   2021.03   동대문구   2,802   2,838   2,766   2,778
7   2021.03    중랑구   2,534   2,595   2,860   2,792
8   2021.03    성북구   3,180   3,581   3,386   3,563
9   2021.03    강북구   1,865   1,937   2,121   2,165
10  2021.03    도봉구   1,831   1,923   2,122   2,197
11  2021.03    노원구   3,075   3,297   3,479   3,570
12  2021.03    은평구   2,859   3,162   3,231   3,420
13  2021.03   서대문구   2,252   2,678   2,455   2,635
14  2021.03    마포구   3,104   3,495   3,162   3,624
15  2021.03    양천구   3,048   3,114   3,256   3,146
16  2021.03    강서구   4,708   5,029   4,733   4,758
17  2021.03    구로구   2,591   2,584   2,685   2,736
18  2021.03    금천구   1,732   1,656   1,766   1,674
19  2021.03   영등포구   3,027   3,179   3,129   3,091
20  2021.03    동작구   3,504   3,741   3,326   3,530
21  2021.03    관악구   5,001   4,970   5,193   5,055
22  2021.03    서초구   2,914   3,188   3,392   3,735
23  2021.03    강남구   4,298   4,570   4,954   5,191
24  2021.03    송파구   5,079   5,574   6,230   6,513
25  2021.03    강동구   4,826   5,116   3,876   3,947

In [15]:
pd1['총전입'] = pd1['전입 남자'] + pd1['전입 여자']

In [16]:
pd1['총전출'] = pd1['전출 남자'] + pd1['전출 여자']

In [18]:
pd1

         기간    자치구   전입 남자   전입 여자   전출 남자   전출 여자           총전입           총전출
0   2021.03  서울특별시  73,389  78,228  77,842  79,991  73,38978,228  77,84279,991
1   2021.03    종로구   1,266   1,378   1,353   1,344    1,2661,378    1,3531,344
2   2021.03     중구     949   1,017   1,075   1,069      9491,017    1,0751,069
3   2021.03    용산구   2,111   2,351   1,942   1,940    2,1112,351    1,9421,940
4   2021.03    성동구   2,282   2,374   2,575   2,466    2,2822,374    2,5752,466
5   2021.03    광진구   2,551   2,881   2,775   3,052    2,5512,881    2,7753,052
6   2021.03   동대문구   2,802   2,838   2,766   2,778    2,8022,838    2,7662,778
7   2021.03    중랑구   2,534   2,595   2,860   2,792    2,5342,595    2,8602,792
8   2021.03    성북구   3,180   3,581   3,386   3,563    3,1803,581    3,3863,563
9   2021.03    강북구   1,865   1,937   2,121   2,165    1,8651,937    2,1212,165
10  2021.03    도봉구   1,831   1,923   2,122   2,197    1,8311,923    2,1222,197
11  2021.03    노원구   3,075   3,297   3,479   3,570    3,0753,297    3,4793,570
12  2021.03    은평구   2,859   3,162   3,231   3,420    2,8593,162    3,2313,420
13  2021.03   서대문구   2,252   2,678   2,455   2,635    2,2522,678    2,4552,635
14  2021.03    마포구   3,104   3,495   3,162   3,624    3,1043,495    3,1623,624
15  2021.03    양천구   3,048   3,114   3,256   3,146    3,0483,114    3,2563,146
16  2021.03    강서구   4,708   5,029   4,733   4,758    4,7085,029    4,7334,758
17  2021.03    구로구   2,591   2,584   2,685   2,736    2,5912,584    2,6852,736
18  2021.03    금천구   1,732   1,656   1,766   1,674    1,7321,656    1,7661,674
19  2021.03   영등포구   3,027   3,179   3,129   3,091    3,0273,179    3,1293,091
20  2021.03    동작구   3,504   3,741   3,326   3,530    3,5043,741    3,3263,530
21  2021.03    관악구   5,001   4,970   5,193   5,055    5,0014,970    5,1935,055
22  2021.03    서초구   2,914   3,188   3,392   3,735    2,9143,188    3,3923,735
23  2021.03    강남구   4,298   4,570   4,954   5,191    4,2984,570    4,9545,191
24  2021.03    송파구   5,079   5,574   6,230   6,513    5,0795,574    6,2306,513
25  2021.03    강동구   4,826   5,116   3,876   3,947    4,8265,116    3,8763,947